### ISSUE TITLE
Can't install since xCode 7.1.1 update 

### ISSUE THREAD

**Issue by Maxatma** [alcatraz/Alcatraz#387] opened 2015-11-17 11:31 UTC
I were trying to install it / clone+build, doesn't work. Nothing changes. 
Xcode Version 7.1.1 (7B1005)

**Comment by ngothanhtai** [comment] 2015-11-17 12:59
I have same problem.

**Comment by jurre** [comment] 2015-11-17 13:00
What version of Alcatraz do you currently have installed?

**Comment by c-mendoza** [comment] 2015-11-17 15:40
I have the same issue on Xcode 7.0.1 and Alcatraz 1.1.13

**Comment by ngothanhtai** [comment] 2015-11-17 16:18
I reinstalled and it works. Maybe the first time I ignore this message.
https://gyazo.com/a19db2bbec47c04b0ecf6c34dbeaa168

**Comment by sam-wan** [comment] 2015-11-18 00:22
I have the same issue.

I have uninstalled Alcatraz (using the instruction on the website) and reinstalled.  No luck

**Comment by hugovanderlei** [comment] 2015-11-18 12:58
same problem here

**Comment by ForkPanda** [comment] 2015-11-19 02:26
I have the same problem on Xcode 7.1.1 & Alcatraz 1.1.13

**Comment by w9174760** [comment] 2015-11-19 03:15
I have the same issue.

**Comment by yuan232007** [comment] 2015-11-19 06:19
I have the same problem on Xcode 7.1.1 and the Alcatraz new version

**Comment by yyny1789** [comment] 2015-11-19 07:01
I have same problem.

**Comment by Maxatma** [comment] 2015-11-19 10:46
uninstall + install helped me today)

**Comment by danishin** [comment] 2015-11-20 06:23
+1

**Comment by candledragle** [comment] 2015-11-21 09:10
I have the same problem on Xcode 7.1.1

**Comment by yangtaoNewGame** [comment] 2015-11-21 17:32
@ngothanhtai , I select load bounds  ...but still can't  install any plugin ..   why ?

**Comment by yangtaoNewGame** [comment] 2015-11-22 15:09
I updated mac os capitan ,  xcode could installed plugin ...   if anyone like me , you may try it.

**Comment by NSRover** [comment] 2015-11-24 08:06
What worked for me was completely removing Alcatraz first. Then I cloned the repo and build the project myself from Xcode. 

Next I installed the VVDocumenter plugin and it works fine now.

**Comment by fvvliet** [comment] 2015-11-25 08:32
same same

**Comment by rizwankce** [comment] 2015-11-26 09:12
Cloning the Repo and build the project brings back Package Manager option.

**Comment by fvvliet** [comment] 2015-11-26 09:16
@rizwankce : sorry, it does not.

**Comment by rizwankce** [comment] 2015-11-26 09:21
@fvvliet I have followed these steps.
- Removed all files related to Alcatraz
- Cloned Repo and build using xCode
- Quit the xCode and reopened.
- Clicked "Load Bundle" when the xCode asked

**Comment by fvvliet** [comment] 2015-11-26 09:22
@rizwankce : Ok I'll try again, thanks

**Comment by ForkPanda** [comment] 2015-11-26 16:29
I have already solved the problem.

And I write a shell script to reload all of Xcode plug-ins.

[Portal Here!](https://github.com/ForkPanda/RescueXcodePlug-ins)

It works for me.

**Comment by hugovanderlei** [comment] 2015-11-26 17:17
Thanks @ForkPanda! it works!

**Comment by yyny1789** [comment] 2015-11-27 04:00
Thanks @ForkPanda!

**Comment by virenenskully** [comment] 2015-12-07 06:39
thanks ForkPanda!

**Comment by GarveyCalvin** [comment] 2015-12-07 07:48
Thank you. @rizwankce 
It works!

**Comment by pitkane** [comment] 2015-12-11 21:30
Thank you @ForkPanda, works like a charm :)

**Comment by xiaonan0527** [comment] 2015-12-16 10:30
thank you @ForkPanda

**Comment by guillaume-algis** [comment] 2016-03-26 17:27
The issue was probably caused by two things:

- Alcatraz being added to the "skipped plugins" list of Xcode, which was fixed in #315
- All plugins not including the new Xcode UUID just after its release, which is still a problem, but progress on this will be tracked in #442 

Closing as this is becoming a "thank you" thread :). Please leave a comment if you feel this issue was not yet fixed and this should be left open. Thanks everyone!

**Closed by guillaume-algis** 2016-03-26 17:27 UTC
