### ISSUE TITLE
Installation OK but didn't appear in xcode 8.2.*

### ISSUE THREAD

**Issue by DarkChyper** [alcatraz/Alcatraz#513] opened 2017-03-29 16:30 UTC
Hi, the issue which talk about this problem is closed so i open another one.
There is my console view : 
curl -fsSL https://raw.github.com/alcatraz/Alcatraz/master/Scripts/install.sh | sh
Password:
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   590    0   590    0     0    430      0 --:--:--  0:00:01 --:--:--   430
  0  107k    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0x Alcatraz.xcplugin/
x Alcatraz.xcplugin/Contents/
x Alcatraz.xcplugin/Contents/Info.plist
x Alcatraz.xcplugin/Contents/MacOS/
x Alcatraz.xcplugin/Contents/Resources/
x Alcatraz.xcplugin/Contents/Resources/ATZPackageListTableCellView.nib
x Alcatraz.xcplugin/Contents/Resources/ATZPluginWindowController.nib
x Alcatraz.xcplugin/Contents/Resources/bitbucket_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/
x Alcatraz.xcplugin/Contents/Resources/eye_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/git_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/github_grayscale.tiff
x Alcatraz.xcplugin/Contents/Resources/link_icon.tiff
x Alcatraz.xcplugin/Contents/Resources/en.lproj/InfoPlist.strings
x Alcatraz.xcplugin/Contents/Resources/en.lproj/Localizable.strings
100  107k  100  107k    0     0  39000      0  0:00:02  0:00:02 --:--:--  249k

Alcatraz successfully installed!!1!🍻  Please restart your Xcode (8.2.1).

but nothing appear in xcode :(

**Comment by ArpiJakab** [comment] 2017-03-29 22:20
Same problem.

**Comment by NotAlexNoyle** [comment] 2017-03-30 01:49
Same issue

**Comment by jurre** [comment] 2017-03-30 06:19
This is most likely a duplicate of #475, please read through that.

**Closed by jurre** 2017-03-30 06:19 UTC
