### ISSUE TITLE
Version 7.1.1 (7B1005) cannot install it . I got it when I updated xcode to this version. Version 7.0.1 was OK

### ISSUE THREAD

**Issue by 060302** [alcatraz/Alcatraz#389] opened 2015-11-19 08:27 UTC

**Comment by kattrali** [comment] 2015-11-19 16:26
Hi @060302! Thank you for the report. This is being closed as a duplicate of #387, where you can monitor further progress.

**Closed by kattrali** 2015-11-19 16:26 UTC
