### ISSUE TITLE
Visually mark inactive plugins

### ISSUE THREAD

**Issue by revolter** [alcatraz/Alcatraz#401] opened 2015-12-10 13:31 UTC
Could Alcatraz check the `Info.plist` files of the installed (and uninstalled) plugins and tell the user that the respective plugins doesn't have his Xcode's version's UUID so it is Installed but actually is not loaded and running?

**Comment by guillaume-algis** [comment] 2015-12-10 14:05
Dupe of #195.
Related to #303.

**Closed** 2015-12-10 15:18 UTC
Labels: duplicate
