### ISSUE TITLE
Filter button label vertical alignment eventually wrong

### ISSUE THREAD

**Issue by hlfcoding** [alcatraz/Alcatraz#412] opened 2015-12-30 06:04 UTC
![image](https://cloud.githubusercontent.com/assets/100884/12046962/0785a63c-ae78-11e5-9741-54305aa6f069.png)

I found that after clicking around and doing an install.

**Comment by guillaume-algis** [comment] 2016-03-26 16:35
Hi @hlfcoding, thanks for the report!
On which OS X, Xcode and Alcatraz versions are you seeing this (if you're still seeing it)?

**Comment by hlfcoding** [comment] 2016-03-26 17:04
I'm no longer seeing it. Now running 1.1.18 on Xcode 7.3 and OS X 10.11.4. The bug was found in Xcode 7.2, OS X 10.11.2, and whichever version of Alcatraz was out at that time.

**Comment by guillaume-algis** [comment] 2016-03-26 17:15
Thanks for the quick feedback!

I'm closing as I am unable to reproduce on neither Xcode 7.2 or 7.3 and this seems fixed for you too. Feel free to update this issue if you run into the bug again and I'll reopen.

**Closed by guillaume-algis** 2016-03-26 17:15 UTC
