### ISSUE TITLE
Xcode 8 won't load plug-ins

### ISSUE THREAD

**Issue by 0xced** [alcatraz/Alcatraz#475] opened 2016-06-13 22:00 UTC
[Joe Groff tweet](http://twitter.com/jckarter/status/742471686935568384)
> @fzwob Xcode 8 uses library validation. It won't load in-process plugins anymore.

That’s very bad news for Alcatraz and the current plug-ins ecosystem. 😢

**Comment by alanhamlett** [comment] 2016-06-14 08:35
I'm looking for docs on creating Xcode Source Editor Extensions... anyone find them yet?

> Xcode 8 adds support for Xcode Source Editor Extensions: Application Extensions provide additional
commands in the Xcode Editor menu. These extensions can manipulate both text and selections. To
create them, use the new Xcode Source Editor Extension target template in the macOS Application
Extensions section when creating a project. (23194974)

I don't have the `Xcode Source Editor Extension` target template in my Xcode 8 Beta, but I did find this:

https://gist.github.com/OdNairy/62de23d6627d518c38fed078a0581046

**Comment by 0xced** [comment] 2016-06-14 08:59
To create an Xcode Source Editor Extension, you have to add a new target to a project.

Unfortunately, as its name imply, a *Source Editor Extension* only has access to the source code editor part of Xcode. So only a few plug-ins can be rewritten with the new official extension API. 😢

**Comment by fzwo** [comment] 2016-06-14 09:03
In his tweets to me, Joe Groff asked for radars for missing functionality, implying that they are interested in giving us a powerful system. So I’d invite every dev whose plug-in is not supported under the new system to file radars.

f.

**Comment by erikolofsson** [comment] 2016-06-14 12:41
This is very unfortunate. For the plugins that I need I would suspect a very small portion of the functionality is feasible with the new plugin infrastructure.

A workaround is to remove the signature from Xcode.app. You can do this with https://github.com/steakknife/unsign

**Comment by fzwo** [comment] 2016-06-14 12:44
@neonichu [tweets](https://twitter.com/NeoNacho/status/742653816194007040) that the template shows up when adding a new target to an existing macOS project.

**Comment by guillaume-algis** [comment] 2016-06-14 14:32
@erikolofsson I doubt this would solve the problem. Even if being itself unsigned, Xcode will probably refuse to load unsigned code.
Maybe you could tamper with the extension loading function once Xcode's signature is removed, but that would probably also implies disabling SIP... And well this doesn't seems like a good idea at all.

**Comment by pdcgomes** [comment] 2016-06-14 14:41
@guillaume-algis I tired it a couple of hours ago and it did work.

**Comment by guillaume-algis** [comment] 2016-06-14 15:30
@pdcgomes you mean unsigning Xcode with https://github.com/steakknife/unsign to make it load arbitrary plugins?
To be honest I'm at work and I didn't not yet have time to play with the thing much. That was just random thoughts on the matter ;)

**Comment by pdcgomes** [comment] 2016-06-14 15:45
Yes, correct. But agreed, not the way forward. I'm just concerned with how fast they'll be able to push additional extension points. We shall see!

**Comment by pdcgomes** [comment] 2016-06-15 05:22
Managed to sit down with some of the Xcode engineers that are working on Xcode Extensions earlier today. As expected, anything that doesn't involve pure text manipulation can't really be achieved with the current extension point. 
The good news is that this is just the beginning and they're very keen on getting as much feedback as they possibly can, so definitely submit radars with very clear use case cases.

Unfortunately there are no clear timelines, so who knows how long it'll take until we have a rich public API and more extension points.

And yes, they've confirmed that by removing code signing, existing plugins will work. Having that said, it adds even more friction to the whole process, so the average user will probably either opt out or just be completely unaware of it. The way forward is to definitely clearly document valid use cases and file radars.

Both sad times and exciting times ahead.

**Comment by dabing1022** [comment] 2016-06-17 06:32
[Xcode Extensions- Your Life Will Change](http://cleanswifter.com/xcode-extensions/)

**Comment by alanhamlett** [comment] 2016-06-17 11:06
Looks like the user has to invoke new extensions from a menu or keyboard shortcut. This is a bummer.

**Comment by JasonWorking** [comment] 2016-06-18 06:14
Bad news.~

**Comment by borisyurkevich** [comment] 2016-06-18 12:09
Good news, Xcode 8 protected from old dangerous plugins. Stop thinking about yourself and think about the greater good. We all get safer tool. Horrible story with Xcode Ghost should never happen again. Please don't break Xcode signature. Remember that's priority should be to create great products, not making your development live more fun and pleasant.

**Comment by alanhamlett** [comment] 2016-06-18 17:39
@borisyurkevich the new api is not yet ready but they disabled the current one anyway.

We all want secure plugins, but the way Apple disabled the current plugins without providing a sufficient replacement is why this is bad news.

**Comment by antgly** [comment] 2016-06-18 19:49
@alanhamlett Apple Maps

**Comment by alanhamlett** [comment] 2016-06-18 20:58
No point in arguing why Apple does things, let's just file Radars for the extension features we need and hope they get implemented:

https://bugreport.apple.com/

**Comment by BeauNouvelle** [comment] 2016-06-19 23:45
It would have been nice if we were given a transitionary period at least. Given time to port the plugins we have that will work with the new system, AND given time to submit radars for the added functionality. Everything we have built is pretty much dead overnight.

I'm glad we now have colors, and documentation creation built in to Xcode 8, as they were my most used plugins.

At least we'll be able to sell them on the mac store right?

**Comment by ianmasters** [comment] 2016-06-20 02:40
@BeauNouvelle
> It would have been nice if we were given a transitionary period at least.

This is Xcode 8 beta; by it's very definition the transitory period! Your feedback to Apple as they push toward public release is critical to make them aware of what you think should be done.

**Comment by iphone-andy** [comment] 2016-06-20 06:27
So why xcode8 can't load old plugins , Is there any hack ideal to fix it

**Comment by ianmasters** [comment] 2016-06-20 07:03
@iphone-andy it's to prevent executing potentially unsafe / insecure / unsigned code that could be malicious or otherwise.

**Comment by Isuru-Nanayakkara** [comment] 2016-06-22 06:50
@borisyurkevich I've used plug-ins extensively and never came across any "dangerous" plug-ins. Third party plug-ins is what made Xcode, otherwise a terrible IDE, tolerable. What Apple should have done is provide a way to sign Xcode plug-ins instead of disabling everything altogether.

**Comment by BeauNouvelle** [comment] 2016-06-22 07:05
I've already filed a bug report about it. I'm sure if enough of us say something they'll at least give us more time to transition.

**Comment by borisyurkevich** [comment] 2016-07-04 20:01
@Isuru-Nanayakkara issue is not in current plugins but in the fact that Xcode allows not signed code. This lead to the Xcode ghost attack. BTW used many IDE's and Xcode is way ahead of everything else. I shipped many apps and never felt a need to install a plugin.

**Comment by erikolofsson** [comment] 2016-07-04 20:14
I think we could keep using the current plugin system safely by:
* Create self signed certificate and add it as trusted to Key Chain
* Walk through all of Xcode.app and find all internal plugins
   * Verify the signature of the plugin against the Xcode main app signature
   * If verified put in list of verified plugins
* Resign Xcode.app (and optionally xcodebuild) and all verified plugins with the self signed certificate
* Sign all of the custom plugins you want to use with the self signed certificate.

**Comment by osolo** [comment] 2016-07-08 15:35
<rant>
I am personally quite upset by this change.  Hardening Xcode.app doesn't fix the Xcode Ghost problem, it just forces malicious parties to move elsewhere in the toolchain.  I can think of 10 different ways to inject bad code that doesn't involve changing Xcode.  

On the other hand, Xcode is now broken for me.  I use 5-10 plugins from Alcatraz and Xcode 8 will suck without them.  I have to disable the whole OS's system protection to get them back.  How does THAT help security?  

Also, if you watch the WWDC session, you see how concerned the Xcode team was about performance of plugins.  This is such a non-issue.  I've both used and written plugins for Xcode and other IDEs (namely Visual Studio) and this has never been a real issue.  But now the IPC approach I'm afraid we can never things like real time code editing in plugins.  Too bad.  RIP plugins.
</rant>

**Comment by lechium** [comment] 2016-07-18 15:49
i am absolutely disgusted with this decision. Xcode ghost had NOTHING to do with plugins. this is just another one of those decisions treating everyone like the lowest common denominator. this "safety first" mentality that has destroyed any possibility of swift being a useful language is infecting all of their other decisions across the board. its making me seriously reconsider my line of work.

The engineers shouldn't be worried about plugin performance, its OUR choice to use them, and it should remain OUR choice, if it hinders performance, thats OUR problem, not theirs. This reeks of sony's PS3 other OS debacle.

**Comment by iandundas** [comment] 2016-07-18 16:35
lol. On the other hand, we're presumably going to see an expanding and fully-supported extensions API instead of a pyramid of unstable hacks which is how plugins were developed before.

**Comment by lechium** [comment] 2016-07-19 16:57
i prefer the unstable hacks since it brings the ability to tweak, fix and improve ANY part of Xcode. Im so fed up with their new cultural shift, It's one thing to treat end users like knuckle-dragging morons, treating developers like this is completely unacceptable.

**Comment by guillaume-algis** [comment] 2016-07-19 17:04
While I understand the frustration, let's try to keep the conversation civil, and focused on how we can make the most of this decision please 😊

Ranting about Apple being closed and secretive will take us nowhere. Thanks! 👍

**Comment by lechium** [comment] 2016-07-19 18:27
fair enough, sorry. just wish there was a way to get them to reverse course on these decisions. i know all my plugins ive authored that i use daily arent going to work with the extensions. i think my only solution personally is to stick with xcode 7.

**Comment by BeauNouvelle** [comment] 2016-07-20 01:04
Submit a radar about it. Apple won't know how upset you are by writing about it here. Let them know, if enough of us do it, they might be able to come up with something where Xcode can support both in the short term.

**Comment by osolo** [comment] 2016-07-20 12:39
@BeauNouvelle thank you for suggesting something actionable.  I filed a radar this morning, and I hope everyone else on this thread will as well.  The link to file is right here: https://bugreport.apple.com/

**Comment by tbodt** [comment] 2016-07-20 16:42
@osolo Can you post the text of the radar so we can duplicate it?

**Comment by osolo** [comment] 2016-07-20 16:49
@tbodt please see http://openradar.appspot.com/radar?id=4978927382560768

**Comment by osolo** [comment] 2016-07-20 20:05
@guillaume-algis I'm wondering if you have any hard stats you can share about the number of Alcatraz installs in the wild.  Maybe if that number is high enough, it would help sway opinions at Apple.

**Comment by guillaume-algis** [comment] 2016-07-20 20:10
@osolo Nope. We have zero stats appart from the number of Github starts for Alcatraz and each plugin's repo. See https://github.com/alcatraz/Alcatraz/issues/150.

**Comment by osolo** [comment] 2016-07-20 20:13
@guillaume-algis  Doesn't Alcatraz phone home to check for upgrades?  Could that be instrumented?

**Comment by vistatinchao** [comment] 2016-07-22 06:34
are you kidding me

**Comment by Ronaldoh1** [comment] 2016-08-02 18:44
No 😢 this can't be true.

**Comment by guillaume-algis** [comment] 2016-08-03 11:14
@osolo Alcatraz uses git for its update process, but we monitor nothing.
One of the only stat we have is the number of clones during the last few days. This isn't very meaningful, as Alcatraz is installed by downloading a tarball (if you follow the instructions on alcatraz.io), and uses `fetch` not `clone` when updating.

Still, here are the stats I screenshot'd today:

![capture d ecran 2016-08-03 a 13 01 03](https://cloud.githubusercontent.com/assets/1041337/17363470/f387fb04-597a-11e6-8590-19624fdad333.png)

I'd say we average at about ~250 unique cloners per day (which, again, tells us nothing).

You could also check the stats for the releases of Alcatraz [using Github's API](https://help.github.com/articles/getting-the-download-count-for-your-releases/). The latest release, 1.1.18, pushed on March 26 has been downloaded 74548 times so far.

    GET https://api.github.com/repos/alcatraz/alcatraz/releases/2892921

Which gives us a bit more than 570 downloads per day on average. Note that it's hard to interpret this number, as users frequently re-install Alcatraz because of the slightly broken update process (in particular, we handle Xcode version changes very poorly).

**Comment by CurlyHeir** [comment] 2016-08-03 11:56
i created new repo for Xcode extensions [link](https://github.com/CurlyHeir/Xcode-Editor-Extensions) , feel free to update it with your ported extensions. it's just repo that collects useful extensions. 
I hope that closing Alcatraz will not affect badly community building add-ons for poor Xcode.

**Comment by capnslipp** [comment] 2016-08-07 20:08
FWIW, using `unsign` on `/Applications/Xcode-beta.app/Contents/MacOS/Xcode` as @erikolofsson's suggested plus adding the beta Xcode's UUID to Alcatraz and other plugs per #73 works flawlessly for me.

Of course, this reduces the security of Xcode.  For my usage though I'm not worried; I primarily use Alcatraz for color schemes and currently have only one true plugin installed— [SCXcodeMinimap](https://github.com/stefanceriu/SCXcodeMiniMap).

Is unsigning dev tools dangerous?  _Maybe._  
Is it the end of open-source add-ons/hacks to Apple apps?  _No, not really._  
Is it just the reality of Apple's protect-novice-users-while-still-technically-allowing-expert-usage?  _Yup._

**Comment by FalconTT** [comment] 2016-08-17 19:51
Well, I just posted a Apple Bug Report for my plugin; hopefully more developers will do the same thing and Apple will listen.

**Comment by alanhamlett** [comment] 2016-08-19 15:36
This app gives unsign an easy to use GUI:
https://github.com/fpg1503/MakeXcodeGr8Again

**Comment by tbodt** [comment] 2016-08-20 21:13
`unsign` isn't really necessary:

    codesign --remove-signature /Applications/Xcode\ beta.app

`--remove-signature` is an undocumented option.

**Comment by tbodt** [comment] 2016-08-20 21:31
A little-known fact about GitHub releases is that there is a download counter. It's not visible in the UI, but you can get it through the GitHub API at https://api.github.com/repos/alcatraz/Alcatraz/releases.

| Version | Download Count |
-------|-------
| 1.1.18 | 81,240 |
| 1.1.17 | 5,710 |
| 1.1.16 | 15,512 |
| 1.1.15 | 47,828 |
| 1.1.14 | 157 |
| 1.1.13 | 18,386 |
| 1.1.12 | 7,139 |
| 1.1.11 | 12,030 |
| 1.1.10 | 52,931 |
| 1.1.9 | 76 |
| 1.1.8 | 25,413 |
| 1.1.7 | 1333 |
| 1.1.6 | 37,751 |
| 1.1.5 | 22,576 |
| 1.1.4 | 2,990 |
| 1.1.3 | 393 |
| 1.1.2 | 18,413 |
| 1.1.1 | 4,931 |
| 1.1 | 10,017 |
| 1.0.9 | 23,546 |
| 1.0.8 | 19,232 |
| 1.0.7 | 11,897 |
| 1.0.6 | 2,086 |
| 1.0.4 | 31,383 |
| 1.0.3 | 39 |
| 1.0.1 | 45,320 |

**Comment by inket** [comment] 2016-08-21 00:34
> unsign isn't really necessary:
> 
> codesign --remove-signature /Applications/Xcode\ beta.app
> --remove-signature is an undocumented option. It does exactly what you think it does.

I believe `codesign --remove-signature` is fundamentally different from `unsign`.

When implementing Xcode unsigning in [update_xcode_plugins](https://github.com/inket/update_xcode_plugins), I tried going the `codesign --remove-signature` way at first, but Xcode seemed to lose access to the system keychain and couldn't login to the accounts in Preferences > Accounts > Apple IDs, so you would have to enter all your Apple ID passwords on every Xcode restart.

**Comment by nrbrook** [comment] 2016-09-12 22:37
I've scripted the process of unsigning Xcode and updating the UUID in plugins. Feedback appreciated. https://github.com/nrbrook/MakeXcodePluginsWork

**Comment by michalzelinka** [comment] 2016-09-13 06:41
My rdar contribution; do not hesitate to express your own mind:

Xcode is a primary tool for the development on all Apple platforms. People can either love or hate it, the fact is it's still the most powerful development tool around.

Lots of its power and usefulness has been achieved by 3rd-party plugins, later covered by the Alcatraz project, which is the number one extension management system for Xcode, as vital and needed as for example npm is needed for Node.js. It's all based on a fair, aware community developing its helpful open-source extras and publishing them on GitHub. It's not a code-injecting ghetto targeting infecting stuff. It's a community within a community.

Xcode 8 tends to drop support for these plugins, most often being narrated as a security step in favour of preventing distribution of injected stuff. This is false; you simply can't prevent that 'cause there's always someone who finds the way. This step simply makes Xcode was less usable, complicated and not that feature-rich. There are many important plugins which developers love, contribute and move forward to make Xcode even better, tell yourself honestly, mostly even better than you could in a short period.

The community needs powerful stuff. Way more powerful than basic source-editing magic. Please reconsider this step in a spirit of community and support to your developers.

In last years, there's a move towards closing your platform. First shutting down Spotlight plugins and its great Flashlight plugins manager, which is simply great and now I need to disable Rootless to use it. Now it's Xcode plugins. You're doing more and more to make developers and power users feel sad and not having their computing device in their hands.

There's a detailed discussion on Alcatraz repo, it says everything:
https://github.com/alcatraz/Alcatraz/issues/475

I'm attaching a list of great plugins I simply can't spend a day without:

AxeMode – Xcode issues patching
Backlight – active line highlighting
ClangFormat – code formatter
DerivedData Exterminator – daily need getting rid or bad stuff
FuzzyAutocomplete – name says it all, still more powerful than Xcode completion
HighlightSelectedString
MCLog – console log filtering, including regexes
OMColorSense
Polychromatic – variables colouring, cute stuff
RSImageOptimPlugin – processing PNG files before committing
SCXcodeMinimap – love this SublimeText-thingy!
XCFixin_FindFix – fixing Find features
XcodeRefactoringPlus – patching Refactor functionality, still buggy, but less than Xcode without plugin
XToDo – TODOs collection
ZLGotoSandbox – 'cause dealing with your folders would be a hell without it

Most of them are not source code-related, thus deserve having a way to be loaded and working like a charm again.

**Comment by EchoZuo** [comment] 2016-09-14 06:13
Xcode 8 can not be installed Alcatraz，
How to do it?

**Comment by jurre** [comment] 2016-09-14 10:39
@EchoZuo please read the thread, plugins are no longer supported in Xcode

**Comment by kaphacius** [comment] 2016-09-14 10:40
@jurre they are, just not as easy to install

**Comment by jurre** [comment] 2016-09-14 11:02
Having to unsign xcode is not supported IMO :)

**Comment by kaphacius** [comment] 2016-09-14 11:05
by whom?)

**Comment by nrbrook** [comment] 2016-09-14 11:11
It hangs even with no plugins activated, just unsigned.

**Comment by Sephiroth87** [comment] 2016-09-14 11:36
A plugin could probably fix that 🤔

**Comment by chrisbirch** [comment] 2016-09-14 20:28
This is indeed terrible news. How can they have done this to us..?

Now, my once tolerable workflow lies broken and lifeless on the floor. Arghhh

**Comment by AlexKvazos** [comment] 2016-09-14 23:49
Should I have hope that Alcatraz will soon work with some patches? Or should I just give up and accept a miserable life since right now?

**Comment by capnslipp** [comment] 2016-09-15 00:08
Can we close this issue now?  The core issue _“Xcode 8 won't load plug-ins”_ has now been fixed as best Alcatraz can fix it.  What remains is gripes about Apple's platform choices, which belong in rdars, on Twitter, and at WWDC conversations, not here.

**Comment by andytriboletti** [comment] 2016-09-15 11:53
I ran the install script with Xcode 8 installed. I don't see "Package Manager" in the Window menu. :(

**Comment by guillaumealgis** [comment] 2016-09-15 12:46
@andytriboletti please read the thread.

**Comment by kattrali** [comment] 2016-09-15 14:29
Let’s close this up now, per #488.

**Closed by kattrali** 2016-09-15 14:29 UTC
