### ISSUE TITLE
 I removed and reinstalled alcatraz , but still can't install any plugin  in Xcode 7.1.1

### ISSUE THREAD

**Issue by yangtaoNewGame** [alcatraz/Alcatraz#390] opened 2015-11-21 17:28 UTC
my mac only have one xcode , path is " /Applications/Xcode.app/Contents/Developer " .   Is anyone could hele me  ?

**Comment by ForkPanda** [comment] 2015-11-27 04:12
[Portal Here! A script for reload all plugin-ins](https://github.com/ForkPanda/RescueXcodePlug-ins)

**Comment by cerniuk** [comment] 2015-11-29 13:38
Same issue.

Found that Alcatraz, upon "install" downloads the code base and project for a plugin to a directory here:

path://~/Library/Application%20Support/Alcatraz/Plug-ins

Then Alcatraz seems to built the plugin. The build will put the plugin into the Xcode plugins directory here:

path://~/Library/Application%20Support/Developer/Shared/Xcode/Plug-ins

Where Alcatraz is failing seems to be the build.  You can manually open up the project that Alcatraz downloaded and build it by going to the:

path://~/Library/Application%20Support/Alcatraz/Plug-ins

folder, opening up one of the projects and then just build it.

Bear in mind some projects have poorly constructed project files that assume the location of Xcode. I have my Xcode organized into a folder in the Applications folder and the "location assumption" problem on occasion.  You can either modify the "make" to adjust the location or create a symlink for Xcode at the root of your Applications folder and then 

setfile -P V thefilepath

-P is important as it tells setfile to make the symlink invisible, not the file that the symlink points to. That lets careless built system "assume" the position of Xcode.

**Comment by wtuyp** [comment] 2015-12-07 09:36
@ForkPanda
Good job!

**Comment by xieweizhi** [comment] 2015-12-11 16:51
@ForkPanda 
Wonderful.

**Comment by Sega-Zero** [comment] 2016-03-22 21:31
@ForkPanda saved my day, thank you. Could you PR your script to this repo, so anyone could cure too?

**Comment by guillaume-algis** [comment] 2016-03-22 22:39
@Sega-Zero @ForkPanda  This has already be discussed many times (probably after each Xcode update) and using this kind of script is a bad idea (though you're welcome to run it on your machine; but it will probably never make it into Alcatraz, or at least not in this form).

Xcode requires plugins to have its UDID in their plist file to ensure the plugin is compatible (ie has been tested by its maintainer) with its latest version. By force-updating all plugins' plists, you're basically saying "I don't care about this mechanism, I'll take the risk of making Xcode unstable". Again, this is fine on your machine, but we won't force all Alcatraz users to do it.

Having said that, I agree Alcatraz still has plenty of room for improvement on this issue. For example, displaying which of the installed plugins do not include the correct Xcode UDID would be a step in the right direction, and I intend to work on that as soon as possible.

I know the UDID issue is a major pita for many Alcatraz users, so any idea on how to better handle this is very welcome :)

**Comment by guillaume-algis** [comment] 2016-03-26 17:09
Closing as OP's initial problem was fixed.

Regarding the root cause, we'll track progress on improving how Alcatraz handles UUIDs in #443. Thanks!

**Closed by guillaume-algis** 2016-03-26 17:09 UTC
