### ISSUE TITLE
Brew support

### ISSUE THREAD

**Issue by mathmatrix828** [alcatraz/Alcatraz#418] opened 2016-01-13 15:17 UTC
I'd like to see this package in Homebrew, if possible. I'd also be willing to collar to get this done

**Comment by guillaume-algis** [comment] 2016-01-13 17:01
Dupe of #142.

**Closed** 2016-01-13 17:02 UTC

**Comment by kattrali** [comment] 2016-01-13 18:32
Not only that, its already done and available via [`brew cask`](https://github.com/caskroom/homebrew-cask/pull/15132).
